#pragma once
#define COLOR_NAMES_DB_PATH    "etc/colornames.bestof.sqlite"
#include "c_fsio/include/fsio.h"
#include "c_string_buffer/include/stringbuffer.h"
#include "c_stringfn/include/stringfn.h"
#include "cargs/include/cargs.h"
#include "colors/colors.h"
#include "db/db.h"
#include "submodules/c_deps/submodules/c_ansi/ansi-codes/ansi-codes.h"
#include "submodules/c_deps/submodules/parson/parson.h"
#include "submodules/c_greatest/greatest/greatest.h"
#include "submodules/log.h/log.h"
#include "submodules/tinydir/tinydir.h"
#include <ctype.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdint.h>
#include <stdio.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdlib.h>
#include <string.h>
#include <string.h>
#include <sys/time.h>
